name: Run Hello AI Script

on: [push]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install numpy pandas matplotlib scikit-learn

      - name: Run hello_ai.py
        run: python hello_ai.py
